export type Product = {
    id:number;
    name:string;
    description:string;
    quantity:number;
    createDate:number;
    updatedDate:number;
    color:string;
    size:string;
    brand:string;
    material:string;
    height:number;
    weigth:number;
    warranty:number;
    price:number;
    imageUrl:string;
    productStatus:string;
    isDeleted:boolean;
    imageList:string[];
}